[2022-03-16 15:09:30,338] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Assignment.Write_into_csv manual__2022-03-16T15:08:17.987720+00:00 [queued]>
[2022-03-16 15:09:30,382] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Assignment.Write_into_csv manual__2022-03-16T15:08:17.987720+00:00 [queued]>
[2022-03-16 15:09:30,384] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 15:09:30,386] {taskinstance.py:1244} INFO - Starting attempt 2 of 2
[2022-03-16 15:09:30,388] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 15:09:30,436] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): Write_into_csv> on 2022-03-16 15:08:17.987720+00:00
[2022-03-16 15:09:30,445] {standard_task_runner.py:52} INFO - Started process 699 to run task
[2022-03-16 15:09:30,453] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Assignment', 'Write_into_csv', 'manual__2022-03-16T15:08:17.987720+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/DAG_file.py', '--cfg-path', '/tmp/tmpy3rwukrr', '--error-file', '/tmp/tmptija4bml']
[2022-03-16 15:09:30,468] {standard_task_runner.py:77} INFO - Job 11: Subtask Write_into_csv
[2022-03-16 15:09:30,617] {logging_mixin.py:109} INFO - Running <TaskInstance: Assignment.Write_into_csv manual__2022-03-16T15:08:17.987720+00:00 [running]> on host e8c8ac0dbee4
[2022-03-16 15:09:30,768] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=Assignment
AIRFLOW_CTX_TASK_ID=Write_into_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-03-16T15:08:17.987720+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-16T15:08:17.987720+00:00
[2022-03-16 15:09:31,405] {logging_mixin.py:109} INFO - {'coord': {'lon': 85.1167, 'lat': 25.6}, 'weather': [{'id': 721, 'main': 'Haze', 'description': 'haze', 'icon': '50n'}], 'base': 'stations', 'main': {'temp': 84.13, 'feels_like': 87.21, 'temp_min': 84.13, 'temp_max': 84.13, 'pressure': 1005, 'humidity': 58}, 'visibility': 4000, 'wind': {'speed': 4.61, 'deg': 40}, 'clouds': {'all': 2}, 'dt': 1647443371, 'sys': {'type': 1, 'id': 9129, 'country': 'IN', 'sunrise': 1647390492, 'sunset': 1647433708}, 'timezone': 19800, 'id': 1260086, 'name': 'Patna', 'cod': 200}
[2022-03-16 15:09:31,407] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/current_wheather_data.py", line 24, in write_csv
    list_item = [data["State"],data["weather"][0]["description"],data["main"]["temp"], data["main"]["feels_like"],
KeyError: 'State'
[2022-03-16 15:09:31,487] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=Assignment, task_id=Write_into_csv, execution_date=20220316T150817, start_date=20220316T150930, end_date=20220316T150931
[2022-03-16 15:09:31,551] {standard_task_runner.py:92} ERROR - Failed to execute job 11 for task Write_into_csv
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/current_wheather_data.py", line 24, in write_csv
    list_item = [data["State"],data["weather"][0]["description"],data["main"]["temp"], data["main"]["feels_like"],
KeyError: 'State'
[2022-03-16 15:09:31,594] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-16 15:09:31,719] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
